### ISSUE TITLE
Contradicting lock files

### ISSUE THREAD

**Issue by Borewit** [linkFly6/Said#33]
Please choose npm or yarn, it is a very a bad idea to keep both lock files:
* NPM lock file: [package-lock.json](https://github.com/linkFly6/said/blob/master/package-lock.json) 
* Yarn lock file: [yarn.lock](https://github.com/linkFly6/said/blob/master/yarn.lock)

**Comment by linkFly6** [comment]
Thank you for your proposal, I will use yarn.
